"""feat : update external_supplier_data

Revision ID: cacdf0c99a44
Revises: 2b6e783d04b4
Create Date: 2025-02-11 14:41:27.805327

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "cacdf0c99a44"
down_revision = "2b6e783d04b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_unique_constraint(
        "supplier_master_ensid_session",
        "supplier_master_data",
        ["ens_id", "session_id"],
    )
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_users_table_user_id", "users_table", ["user_id"], unique=True)
    