"""feat : updation

Revision ID: a8b6d24a6058
Revises: f004c2904592
Create Date: 2025-02-14 17:48:48.938164

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "a8b6d24a6058"
down_revision = "f004c2904592"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "external_supplier_data",
        "country",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "external_supplier_data",
        "location",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "external_supplier_data",
        "website",
        existing_type=postgresql.ARRAY(sa.TEXT()),
        type_=sa.ARRAY(sa.String()),
        existing_nullable=True,
    )
    
    # Use raw SQL to cast the array to JSONB
    op.execute(
        """
        ALTER TABLE external_supplier_data 
        ALTER COLUMN controlling_shareholders_type 
        SET DATA TYPE JSONB 
        USING to_jsonb(controlling_shareholders_type);
        """
    )
    
    op.execute(
        """
        ALTER TABLE external_supplier_data 
        ALTER COLUMN global_ultimate_owner_type 
        SET DATA TYPE JSONB 
        USING to_jsonb(global_ultimate_owner_type);
        """
    )

def downgrade():
    pass