"""feat : updation

Revision ID: ed93ff304032
Revises: a8b6d24a6058
Create Date: 2025-02-14 18:08:49.392572

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "ed93ff304032"
down_revision = "a8b6d24a6058"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("matchbvdid")
    op.drop_table("news_master")
    op.drop_table("orgdata")
    op.add_column(
        "external_supplier_data",
        sa.Column("grid_legal", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.drop_column("external_supplier_data", "gird_legal")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass