"""update upload_supplier_master_data

Revision ID: 645caf088eb3
Revises: 187da614dbc9
Create Date: 2025-01-24 15:46:38.223520

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "645caf088eb3"
down_revision = "187da614dbc9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "upload_supplier_master_data",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uploaded_name", sa.String(), nullable=True),
        sa.Column("uploaded_name_international", sa.String(), nullable=True),
        sa.Column("uploaded_address", sa.Text(), nullable=True),
        sa.Column("uploaded_postcode", sa.String(), nullable=True),
        sa.Column("uploaded_city", sa.String(), nullable=True),
        sa.Column("uploaded_country", sa.String(), nullable=True),
        sa.Column("uploaded_phone_or_fax", sa.String(), nullable=True),
        sa.Column("uploaded_email_or_website", sa.String(), nullable=True),
        sa.Column("uploaded_national_id", sa.String(), nullable=True),
        sa.Column("uploaded_state", sa.String(), nullable=True),
        sa.Column("uploaded_address_type", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("name_international", sa.String(), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("postcode", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("phone_or_fax", sa.String(), nullable=True),
        sa.Column("email_or_website", sa.String(), nullable=True),
        sa.Column("national_id", sa.String(), nullable=True),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("address_type", sa.String(), nullable=True),
        sa.Column("suggested_name", sa.String(), nullable=True),
        sa.Column("suggested_name_international", sa.String(), nullable=True),
        sa.Column("suggested_address", sa.Text(), nullable=True),
        sa.Column("suggested_postcode", sa.String(), nullable=True),
        sa.Column("suggested_city", sa.String(), nullable=True),
        sa.Column("suggested_country", sa.String(), nullable=True),
        sa.Column("suggested_phone_or_fax", sa.String(), nullable=True),
        sa.Column("suggested_email_or_website", sa.String(), nullable=True),
        sa.Column("suggested_national_id", sa.String(), nullable=True),
        sa.Column("suggested_state", sa.String(), nullable=True),
        sa.Column("suggested_address_type", sa.String(), nullable=True),
        sa.Column("ens_id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("bvd_id", sa.String(), nullable=True),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("upload_supplier_master_data")
    # ### end Alembic commands ###
