"""new columns

Revision ID: 641b9c0f2cfb
Revises: 4ac151050dba
Create Date: 2025-02-21 16:49:48.669707

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from sqlalchemy.dialects.postgresql import ENUM
# revision identifiers, used by Alembic.
revision = "641b9c0f2cfb"
down_revision = "4ac151050dba"
branch_labels = None
depends_on = None

# Define the new enum type with 'PENDING' added
new_enum_type = ENUM(
    "VALIDATED",
    "NOT_VALIDATED",
    "NOT_REQUIRED",
    "NO_MATCH",
    "PENDING",
    name="truesightstatus",
    create_type=False,  # Prevent recreation of type if it exists
)

old_enum_type = ENUM(
    "VALIDATED",
    "NOT_VALIDATED",
    "NOT_REQUIRED",
    "PENDING",
    name="truesightstatus",
    create_type=False,  # Use existing enum
)

def upgrade():
    op.add_column(
        "external_supplier_data",
        sa.Column(
            "pr_more_risk_score_ratio",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.add_column(
        "external_supplier_data",
        sa.Column(
            "pr_reactive_more_risk_score_ratio",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.alter_column(
        "upload_supplier_master_data",
        sa.Column(
            "process_status",
            new_enum_type,
            nullable=False,
            server_default="PENDING"
        ),
    )
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass