"""update primary_key

Revision ID: fba331cb6580
Revises: 645caf088eb3
Create Date: 2025-01-24 16:00:49.781944

"""



# revision identifiers, used by Alembic.
revision = "fba331cb6580"
down_revision = "645caf088eb3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
