"""update upload_supplier_master_data

Revision ID: 187da614dbc9
Revises: b7003984185f
Create Date: 2025-01-24 15:43:53.936261

"""



# revision identifiers, used by Alembic.
revision = "187da614dbc9"
down_revision = "b7003984185f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
