"""feat : update Truesight and upload_supplier_master_data

Revision ID: 2e0a114f767e
Revises: ced393304a62
Create Date: 2025-02-07 14:19:29.933169

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM

from alembic import op

# revision identifiers, used by Alembic.
revision = "2e0a114f767e"
down_revision = "ced393304a62"
branch_labels = None
depends_on = None

# Define the new enum type with 'PENDING' added
new_enum_type = ENUM(
    "VALIDATED",
    "NOT_VALIDATED",
    "NOT_REQUIRED",
    "PENDING",
    name="truesightstatus",
    create_type=False,  # Prevent recreation of type if it exists
)

old_enum_type = ENUM(
    "VALIDATED",
    "NOT_VALIDATED",
    "NOT_REQUIRED",
    name="truesightstatus",
    create_type=False,  # Use existing enum
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Alter the existing ENUM to include "PENDING"
    # op.execute("ALTER TYPE truesightstatus ADD VALUE 'PENDING'")
    
    # op.drop_column("session_screening_status", "process_status")
    
     # Add the new column to session_screening_status
    op.add_column(
        "upload_supplier_master_data",
        sa.Column(
            "process_status",
            new_enum_type,
            nullable=False,
            server_default="PENDING"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table(
        "matchbvdid",
        sa.Column("bvdid", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column(
            "name_international",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("address", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "postcode", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("city", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column(
            "country", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "phone_or_fax", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "email_or_website",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "national_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("state", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column(
            "address_type", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "ens_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("ens_id", name="matchbvdid_pkey"),
    )
    # ### end Alembic commands ###
