"""feat : create tables

Revision ID: 70545916e22f
Revises: c2aaa9d1ef10
Create Date: 2025-02-13 18:11:44.642129

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "70545916e22f"
down_revision = "c2aaa9d1ef10"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("company_profile", sa.Column("name", sa.String(), nullable=False))  
    op.add_column("company_profile", sa.Column("location", sa.String(), nullable=False))
    op.add_column("company_profile", sa.Column("address", sa.String(), nullable=False))
    op.add_column("company_profile", sa.Column("website", sa.String(), nullable=False))
    op.add_column("company_profile", sa.Column("active_status", sa.String(), nullable=False))
    op.add_column("company_profile", sa.Column("operation_type", sa.String(), nullable=False))  
    op.add_column("company_profile", sa.Column("legal_status", sa.String(), nullable=False))
    op.add_column("company_profile", sa.Column("national_identifier", sa.String(), nullable=False))
    op.add_column("company_profile", sa.Column("alias", sa.String(), nullable=False))
    op.add_column("company_profile", sa.Column("incorporation_date", sa.Date(), nullable=False))   
    op.add_column("company_profile", sa.Column("shareholders", sa.String(), nullable=False))
    op.add_column("company_profile", sa.Column("revenue", sa.String(), nullable=False))
    op.add_column("company_profile", sa.Column("subsidiaries", sa.String(), nullable=False))
    op.add_column("company_profile", sa.Column("corporate_group", sa.Numeric(), nullable=False))
    op.add_column("company_profile", sa.Column("key_executives", sa.String(), nullable=False))

    
    

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass